name: FeatureCI
on:
  push:
    branches:
      - '!staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo "Only on all branch except staging"
    - name: Run a multi-line script
      run: |
        echo "Only on all branch except staging"
